name: RunCollection

inputs:
  collection_title:
    required: true
    type: string
  postman_api_key: 
    required: true
    type: string
  collection_iud:
    required: true
    type: string
  environment_uid: 
    required: true
    type: string

env:
  PST_API_URL: 'https://api.getpostman.com'
  NEWMAN_RUN_CMD: |
            newman run "$PST_API_URL/collections/${{ inputs.collection_iud }}?apikey=${{ inputs.postman_api_key }}" \
            -e "$PST_API_URL/environments/${{ inputs.environment_uid }}?apikey=${{ inputs.postman_api_key }}" \
            --reporters cli, junit

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 19
          
    - name: Install Newman
      shell: bash
      run: npm install -g newman

    - name: Run newman
      shell: bash
      run: ${{env.NEWMAN_RUN_CMD}}
