name: RunCollection
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 19
          
    - name: Install Newman
      shell: bash
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory
      shell: bash
      run: mkdir -p newman-results

    - name: check inputs
      shell: bash
      run: |
        echo "clc: ${{ matrix.CLC_UID }}"

    - name: Run newman
      shell: bash
      run: |
        newman run "https://api.getpostman.com/collections/${{ matrix.CLC_UID }}?apikey=$PST_API_KEY" -e "https://api.getpostman.com/environments/$ENV_UID?apikey=$PST_API_KEY" -r htmlextra,cli --reporter-htmlextra-export newman-results/htmlreport-${{ matrix.CLC_UID }}.html

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: Postman_Test_Reports
        path: newman-results
