name: RunCollection
inputs:
  PST_CLC_UID:
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 19
          
    - name: Install Newman
      shell: bash
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory
      shell: bash
      run: mkdir -p newman-results

    - name: Run newman
      shell: bash
      env:
        clc: ${{ inputs.PST_CLC_UID }}
      run: |
        newman run "https://api.getpostman.com/collections/$clc?apikey=$PST_API_KEY" -e "https://api.getpostman.com/environments/$ENV_UID?apikey=$PST_API_KEY" -r htmlextra,cli --reporter-htmlextra-export newman-results/htmlreport-${{ matrix.TITLE }}.html
        echo "!!!!!!!!: $clc"

    - name: Upload Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Postman_Test_Reports
        path: newman-results
