name: RunCollection

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 19
          
    - name: Install Newman
      shell: bash
      run: npm install -g newman
