name: RunCollection

inputs:
  postman_api_key: 
    required: true
  collection_iud:
    required: true
  environment_uid: 
    required: true

env:
  PST_API_URL: 'https://api.getpostman.com'
  NEWMAN_RUN_CMD: |
            newman run "$PST_API_URL/collections/$collection_iud?apikey=$postman_api_key" \
            -e "$PST_API_URL/environments/$environment_uid?apikey=$postman_api_key" \
            -r htmlextra --reporter-html-export report.html

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 19
          
    - name: Install Newman
      shell: bash
      run: |
        npm install -g newman
        npm install -S newman-reporter-htmlextra

    - name: Make Directory for results
      shell: bash
      run: mkdir -p testResults

    - name: Run newman
      shell: bash
      run: ${{env.NEWMAN_RUN_CMD}}

    - name: Output the run Details
      uses: actions/upload-artifact@v3
      with:
        name: RunReports
        path: testResults
