name: RunCollection

inputs:
  postman_api_key: 
    required: true
  collection_iud:
    required: true
  environment_uid: 
    required: true

env:
  PST_API_URL: 'https://api.getpostman.com'
  NEWMAN_RUN_CMD: |
            newman run "$PST_API_URL/collections/$collection_iud?apikey=$postman_api_key" \
            -e "$PST_API_URL/environments/$environment_uid?apikey=$postman_api_key" \
            -r cli,junitfull,htmlextra --reporter-htmlextra-browserTitle "Browser title" \
            --reporter-htmlextra-title "Test title"  \
            --reporter-htmlextra-showEnvironmentData \
            --reporter-htmlextra-showGlobalData --reporter-junitfull-export junitReport.xml --reporter-htmlextra-export report.html

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 19
          
    - name: Install Newman
      shell: bash
      run: |
        npm install -g newman
        npm install newman-reporter-junitfull -g
        npm install newman-reporter-htmlextra -g

    - name: Run newman
      shell: bash
      run: ${{env.NEWMAN_RUN_CMD}}

    - name: PublishTestResults@2
      displayName: Publish Test Results
      continueOnError: true
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: reports/junitReport.xml
