name: RunCollection

inputs:
  postman_api_key: 
    required: true
  collection_iud:
    required: true
  environment_uid: 
    required: true

env:
  PST_API_URL: 'https://api.getpostman.com'
  NEWMAN_RUN_CMD: |
            newman run "$PST_API_URL/collections/$collection_iud?apikey=$postman_api_key" \
            -e "$PST_API_URL/environments/$environment_uid?apikey=$postman_api_key" \
            -r htmlextra,cli --reporter-htmlextra-export newman-results/htmlreport.html

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 19
          
    - name: Install Newman
      shell: bash
      run: |
        npm install -g newman
        npm install -S newman-reporter-htmlextra

    - name: Make Directory
      shell: bash
      run: mkdir -p newman-results

    - name: Run newman
      shell: bash
      run: |
        newman run "$PST_API_URL/collections/$collection_iud?apikey=$postman_api_key" \
            -e "$PST_API_URL/environments/$environment_uid?apikey=$postman_api_key" \
            -r htmlextra,cli --reporter-htmlextra-export newman-results/htmlreport.html


    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: Postman_Test_Reports
        path: newman-results
